# Site settings
title: Varm - Desenvolvedor Back End
description: A blog about lorem ipsum dolor sit amet
baseurl: ""
url: ""

# User settings
username: Lorem Ipsum
user_description: Anon Developer at Lorem Ipsum Dolor
email: anon@anon.com
twitter_username: lorem_ipsum
github_username:  lorem_ipsum
gplus_username:  lorem_ipsum

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

plugins:
  - jekyll-feed
  - jekyll-seo-tag

# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - package.json
  - package-lock.json
  - node_modules
  - gulpfile.js
  - src
  - .gitignore
  - Gemfile
  - Gemfile.lock
  - README.md
