# Site settings
title: Varm - Desenvolvedor Back End
description: A blog about lorem ipsum dolor sit amet
baseurl: ""
url: "https://varm.com.br"

# User settings
username: Victor Amorim
user_description: Desenvolvedor Back End
email: victor.rma@gmail.com
twitter_username: victor_rma
github_username:  VictorRMA
gplus_username:  lorem_ipsum

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

plugins:
  - jekyll-feed
  - jekyll-seo-tag

# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - package.json
  - package-lock.json
  - node_modules
  - gulpfile.js
  - src
  - .gitignore
  - Gemfile
  - Gemfile.lock
  - README.md
