# Site settings
title: Varm - Desenvolvedor Back End
description: >
  Um blog sobre desenvolvimento, com o foco em qualidade e aprendizado contínuo.
baseurl: ""
url: "https://varm.com.br"
google_analytics: "UA-131135354-1"
lang: pt_BR

# User settings
username: Victor Amorim
user_description: Desenvolvedor Back End
email: victor.rma@gmail.com
twitter_username: victor_rma
github_username:  VictorRMA

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

plugins:
  - jekyll-feed
  - jekyll-seo-tag

# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

  
# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  # - title: Series
  #   url: /series/
  - title: Tags
    url: /tags/
  - title: Sobre mim
    url: /about/

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - package.json
  - package-lock.json
  - node_modules
  - gulpfile.js
  - src
  - .gitignore
  - Gemfile
  - Gemfile.lock
  - README.md
